version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /repo
    env_file:
      - ./.env
    ports:
      - 8080:8080
    restart: always
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-XGET", "http://localhost:8080/restapi/ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
